// ISO alpha-2 → ISO alpha-3 lowercase (VFS uses 3-letter lowercase codes)
export const ISO2_TO_ISO3: Record<string, string> = {
  AF:'afg', AL:'alb', DZ:'dza', AD:'and', AO:'ago', AG:'atg', AR:'arg', AM:'arm',
  AU:'aus', AT:'aut', AZ:'aze', BS:'bhs', BH:'bhr', BD:'bgd', BB:'brb', BY:'blr',
  BE:'bel', BZ:'blz', BJ:'ben', BT:'btn', BO:'bol', BA:'bih', BW:'bwa', BR:'bra',
  BN:'brn', BG:'bgr', BF:'bfa', BI:'bdi', CV:'cpv', KH:'khm', CM:'cmr', CA:'can',
  CF:'caf', TD:'tcd', CL:'chl', CN:'chn', CO:'col', KM:'com', CG:'cog', CD:'cod',
  CR:'cri', CI:'civ', HR:'hrv', CU:'cub', CY:'cyp', CZ:'cze', DK:'dnk', DJ:'dji',
  DM:'dma', DO:'dom', EC:'ecu', EG:'egy', SV:'slv', GQ:'gnq', ER:'eri', EE:'est',
  SZ:'swz', ET:'eth', FJ:'fji', FI:'fin', FR:'fra', GA:'gab', GM:'gmb', GE:'geo',
  DE:'deu', GH:'gha', GR:'grc', GD:'grd', GT:'gtm', GN:'gin', GW:'gnb', GY:'guy',
  HT:'hti', HN:'hnd', HU:'hun', IS:'isl', IN:'ind', ID:'idn', IR:'irn', IQ:'irq',
  IE:'irl', IL:'isr', IT:'ita', JM:'jam', JP:'jpn', JO:'jor', KZ:'kaz', KE:'ken',
  KI:'kir', KW:'kwt', KG:'kgz', LA:'lao', LV:'lva', LB:'lbn', LS:'lso', LR:'lbr',
  LY:'lby', LI:'lie', LT:'ltu', LU:'lux', MG:'mdg', MW:'mwi', MY:'mys', MV:'mdv',
  ML:'mli', MT:'mlt', MH:'mhl', MR:'mrt', MU:'mus', MX:'mex', FM:'fsm', MD:'mda',
  MC:'mco', MN:'mng', ME:'mne', MA:'mar', MZ:'moz', MM:'mmr', NA:'nam', NR:'nru',
  NP:'npl', NL:'nld', NZ:'nzl', NI:'nic', NE:'ner', NG:'nga', MK:'mkd', NO:'nor',
  OM:'omn', PK:'pak', PW:'plw', PA:'pan', PG:'png', PY:'pry', PE:'per', PH:'phl',
  PL:'pol', PT:'prt', QA:'qat', RO:'rou', RU:'rus', RW:'rwa', KN:'kna', LC:'lca',
  VC:'vct', WS:'wsm', SM:'smr', ST:'stp', SA:'sau', SN:'sen', RS:'srb', SC:'syc',
  SL:'sle', SG:'sgp', SK:'svk', SI:'svn', SB:'slb', SO:'som', ZA:'zaf', SS:'ssd',
  ES:'esp', LK:'lka', SD:'sdn', SR:'sur', SE:'swe', CH:'che', SY:'syr', TW:'twn',
  TJ:'tjk', TZ:'tza', TH:'tha', TL:'tls', TG:'tgo', TO:'ton', TT:'tto', TN:'tun',
  TR:'tur', TM:'tkm', TV:'tuv', UG:'uga', UA:'ukr', AE:'are', GB:'gbr', US:'usa',
  UY:'ury', UZ:'uzb', VU:'vut', VE:'ven', VN:'vnm', YE:'yem', ZM:'zmb', ZW:'zwe',
  PS:'pse', XK:'xkx',
};
